# -*- coding: utf-8 -*-
"""Django_1_1_socket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/nuhin13/91acd5ec23c1766c94ca23af3384cddb/django_1_1_socket.ipynb
"""

import socket

mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
mysock.connect(('data.pr4e.org', 80))
cmd = 'GET http://data.pr4e.org/page2.htm HTTP/1.0\r\n\r\n'.encode()
mysock.send(cmd)

while True:
    data = mysock.recv(512)
    if len(data) < 1:
        break
    print(data.decode(),end='')

mysock.close()